- app/utils/get_filtered_records.py
> Fix response schema of get_filtered_records when columns argument supplied

- app/config.py
- app/namespaces/airtable_scraper/__init__.py
- app/namespaces/airtable_scraper/airtable_scraper_controller.py
- app/namespaces/airtable_scraper/airtable_scraper_schema.py
- app/namespaces/airtable_scraper/airtable_scraper_service.py
Readding legacy airtable_scraper endpoints to ensure backwards compatibility with research
> Readd Airtable Scraper Namespace

- app/namespaces/airtable_scraper/airtable_scraper_controller.py
https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/recpTww5ZJyPlQIp2?blocks=bipIkdtYHmboUfJut 
Update the "server up to date" string that will be shown in the dashboard to be reflective of the last publication date
> Update 'database up to date' date

- app/utils/send_error_email.py
Super small PR to add @rahularoradfs to the email list
> Add Rahul to email list

- app/config.py
> Add port for production config

- README.md
> Update README.md with env variables

- app/namespaces/data_provider/data_provider_controller.py
- app/namespaces/data_provider/data_provider_schema.py
- app/serotracker_sqlalchemy/db_model_config.py
- app/utils/get_filtered_records.py
- added a research_fields boolean param to /records get and post endpoints
- in the get endpoint, this is a request param, in the post endpoint, this is part of the json body
- if set to True, all columns from research source table will be returned as well
- same filtering as before
> Research source endpoint

- app/database_etl/etl_main.py
Reverts serotracker/iit-backend#125
> Revert "Pause research table updates for now"

- app/database_etl/etl_main.py
Reverts serotracker/iit-backend#127
> Revert "Revert "Pause research table updates for now""

- app/database_etl/etl_main.py
Reverts serotracker/iit-backend#128
> Revert "Revert "Revert "Pause research table updates for now"""

- app/namespaces/data_provider/data_provider_service.py
- app/serotracker_sqlalchemy/__init__.py
- app/serotracker_sqlalchemy/db_model_config.py
Changelog:
- Use common list of "dashboard_source_cols" across the record_details and record endpoints
- Ensure that the returned record is always a dict rather than an array of length 1
- Convert dates to isoformat before returning
- Ignore None values in multi select fields
> Fix get record details endpoint

- app/namespaces/meta_analysis/meta_analysis_controller.py
Change logging level for empty records from `error` to `warning`.
N/A
Tested locally
No
> Change logging level for empty records

- app/database_etl/airtable_records_handler/airtable_records_formatter.py
- app/database_etl/etl_main.py
- app/database_etl/location_utils/__init__.py
- app/database_etl/location_utils/country_iso2.json
- app/database_etl/location_utils/location_util_functions.py
- app/database_etl/postgres_tables_handler/__init__.py
- app/database_etl/postgres_tables_handler/table_formatter.py
- app/database_etl/postgres_tables_handler/table_generator.py
1. Pin for study in republic of congo is in the wrong location (democratic republic of congo)
2. The code used to query latlngs is hamly confusing
https://airtable.com/tbli2lWQHAqBa6ZcI/viw7Tba8QVTJ49F4v/recVKB8QV5UpgEBUQ 
1. Run etl
2. Check city/country/state tables, make sure they make sense
3. Run our server and web client locally, made sure things worked fine and that the republic of congo study is in the right place
No.
> Latlng refactor

- app/namespaces/airtable_scraper/airtable_scraper_controller.py
- app/namespaces/airtable_scraper/airtable_scraper_service.py
> Apply changes

- requirements.txt
Add a requirement missed from last merged PR.
> Add requirement

- app/database_etl/tableau_data_connector/table_generator.py
- calls jitter pins in the tableau data generator
> add jitter pins to tableau data generator

- app/database_etl/postgres_tables_handler/postgres_utils.py
Add new filter options, add more useful logging to catch addition/removal of filter options. Adds typing to some existing functions.
N/A, addresses the following ETL log:
Ran ETL locally, tested get_filter_options endpoint.
No.
> Add new filter options, add more useful logging to catch addition/removal of filter options

- app/database_etl/owid_ingestion_handler/owid_data_handler.py
- Automate pulling data from OWID into df instead of saving locally to CSV
- ran ETL, made sure data was pulled correctly
- delete script to refresh OWID data
- remove directory with OWID data csvs
> automate pulling owid data

- app/namespaces/data_provider/data_provider_controller.py
- app/namespaces/data_provider/data_provider_schema.py
> Changing start_date to sampling_start_date and end_date to sampling_end_date

- app/namespaces/meta_analysis/meta_analysis_controller.py
- app/namespaces/meta_analysis/meta_analysis_schema.py
> add new date fields to meta_analysis

- app/database_etl/test_adjustment_handler/test_adjustment_constants.py
Austin, when you test these, double check to make sure that there are no warnings on model compilation!
> add additional model options

- app/database_etl/postgres_tables_handler/postgres_utils.py
> Skip over prioritize_estimates_mode filter type

- app/database_etl/etl_main.py
- app/database_etl/summary_report_generator/__init__.py
- app/database_etl/summary_report_generator/summary_report.py
Sends a summary report detailing each ETL run to slack. For now we've included the following basic functionality:
- Date & time ETL ran
- ETL runtime
- Record count in each table before and after 
- Record count from Airtable
https://airtable.com/tbli2lWQHAqBa6ZcI/viw8iBsG4yooIYvRI/recaU6vCNWIszwnCI
- Tested locally, made sure that correct summary reports were sent to slack
- Specifically, tested that the summary report would be generated even if an error was raised midway through the ETL, causing it to abort
N/A
> WIP: ETL summary report basic features

- app/database_etl/postgres_tables_handler/postgres_utils.py
> Add import to fix crashing filter options

- app/database_etl/airtable_records_handler/airtable_records_formatter.py
- app/database_etl/etl_main.py
- app/database_etl/summary_report_generator/summary_report.py
- app/utils/notifications_sender.py
- added test adjustment stats to the ETL summary report
- put the before and after table counts into a table
- https://airtable.com/tbli2lWQHAqBa6ZcI/viwp6zUTCqlERLzMj/recYhjPCw9l8axi5Y?blocks=hide
- https://airtable.com/tbli2lWQHAqBa6ZcI/viwp6zUTCqlERLzMj/rec60LLkkJRsD3lI6?blocks=hide
- ran ETL successfully and not successfully and checked output in dev logging etl
> Changing ETL summary report

- app/database_etl/test_adjustment_handler/test_adjustment.py
Adjusted prevalence was often diverging to unreasonable values - an unadjusted prevalence p would often converge to an adjusted prevalence 1-p. 
This was occurring because the tolerance for adjusted prevalence probabilities, being based on log probabilities, was unacceptably wide. See the old tolerance at [this link](https://www.wolframalpha.com/input/?i=y+%3D+10%5E%28log10%28x%29+%2B+1%29%2C+y+%3D+10%5E%28log10%28x%29+-+1%29%2C+y+%3D+x++from+x+%3D+0+to+1+and+y+%3D+0+to+1+). I have modified this to use a logit-based tolerance that is more appropriate for probabilities, allowing a constant deviation on the logit scale - which maps out to be smaller deviations for more extreme probabilities and larger deviations for probabilities closer to 0.5. See the new tolerance at [this …
> constrain test adjustment based on logit, not log

- app/database_etl/postgres_tables_handler/postgres_utils.py
Fixes issues with filter options endpoint introduced by city/state filtering
N/A
Tested endpoint locally and tested local serotracker client pointing to local REST service to ensure no regressions.
N/A
> Query unique options from state/city tables instead of dashboard source

- app/database_etl/postgres_tables_handler/table_generator.py
Accidentally merged before pushing commit to address PR feedback. This PR contains that commit
> Hrp income classification

- app/utils/get_filtered_records.py
- Apply distinct function to aggregate query function so that only distinct values are returned in the list
- Tested /records endpoint and /records/sourceid endpoints
- No
> add distinct to aggregate function

- app/database_etl/owid_ingestion_handler/owid_data_handler.py
- app/serotracker_sqlalchemy/db_model_config.py
- Deleted mapping of ordinal vaccine policies to descriptions
- Added vaccination_policy col to be shown in endpoint
> Delete vaccine policy mapping and add column to db model config

- app/database_etl/etl_main.py
- app/database_etl/tableau_data_connector/google_services_manager.py
- app/database_etl/tableau_data_connector/table_generator.py
- migrations/versions/6d154dc9fa83_moving_subgroup_var.py
> fixing migration issue and adding part to update canadian data

- app/database_etl/tableau_data_connector/google_services_manager.py
- app/database_etl/tableau_data_connector/table_generator.py
- using sheet name in range metadata instead to identify the sheet in the spreadsheet to upload to
> changing logic for uploading data to diff google sheets tabs

- app/utils/get_filtered_records.py
Patch to fix inconsistencies between country shading and pins on the dashboard
Tested data provider endpoints using postman, tested webapp pointing to local server
> Add filtering of records without valid latlngs by default

- app/database_etl/airtable_records_handler/airtable_records_formatter.py
Config changes necessary due to airtable schema refactor
N/A
Ran ETL locally and spot checked local DB
N/A
> Config changes necessary due to airtable schema refactor

- app/database_etl/airtable_records_handler/airtable_records_formatter.py
A few more changes to be made to handle airtable schema modifications
> Airtable rearchitecture

- .ebextensions/default.config
- .ebextensions/env.config
- .ebextensions/security-groups.config
- .elasticbeanstalk/config.yml
- .github/workflows/deploy-eb.yml
- README.md
- app/namespaces/healthcheck/healthcheck_controller.py
- app/namespaces/tests/test_data_provider_endpoints.py
Deploys new code pushed to master to our elastic beanstalk environment via github actions.
https://airtable.com/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recUiZV40vRakLoXM?blocks=hide
Tested that pushes to this branch successfully triggered github actions deploy jobs. The url for the environment being deployed to is iit-backend-prod.eba-sdf3d5iy.ca-central-1.elasticbeanstalk.com. 
This is the infrastructure work!!!!
> Add Continuous Deployment to Elastic Beanstalk via Github Actions

- app/database_etl/tableau_data_connector/google_services_manager.py
- Changing Gsheet column range from 10k to 100k
- Ran ETL, didn't get any errors, saw that data was properly loaded in sheet
> Changing Gsheet column range from 10k to 100k

- app/database_etl/airtable_records_handler/airtable_records_getter.py
> Add headers to get_all_records

- app/database_etl/airtable_records_handler/airtable_records_formatter.py
> remove set fork in airtable records formatter file

- app/database_etl/postgres_tables_handler/GBD_mapping_country.csv
Update country mapping to WHO standards (see email chain forwarded).
N/A
N/A
N/A
> Update country mapping

- .github/workflows/push-csv-to-repo.yml
> testing update to workflow

- .github/workflows/push-csv-to-repo.yml
- output/test.csv
> testing yml changes

- .github/workflows/push-csv-to-repo.yml
> clone source repo to get output directory

- .github/workflows/push-csv-to-repo.yml
> added manual trigger

- output/test.csv
> testing test.csv changes

- .github/workflows/push-csv-to-repo.yml
> use copycat action instead

- .github/workflows/push-csv-to-repo.yml
> updated .yml setup with copycat

- .github/workflows/push-csv-to-repo.yml
> trying double upload again

- .github/workflows/push-csv-to-repo.yml
> trying single upload with filter

- output/README.md
- output/test.csv
> removing output folder

- .github/workflows/deploy-eb.yml
> Temporarily pause github action that deploys elastic beanstalk

- app/github_public_repo/estimate_csv_creator.py
- fixes bug related to snake case col in github csv script
> unpack snake case col name from list

- app/config.py
- we are now using the Airtable SOP table in airtable instead of Github CSV fields
> changing airtable data dict link

- app/github_public_repo/estimate_csv_creator.py
> bug fix - dont index snake case column label field

- .github/workflows/push-csv-to-repo.yml
- app/__init__.py
- app/github_public_repo/estimate_csv_creator.py
> Fix push to csv Github action

- app/database_etl/owid_ingestion_handler/owid_data_handler.py
> updating csv url for oxcgrt data

- .github/workflows/ci.yml
> Update CI test script

- .github/workflows/push-csv-to-repo.yml
Python version was incompatible with latest ubuntu so ubuntu version was specified to stable release as per https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/rec4py5yhzTdBGVPp?blocks=hide
> Update GitHub action for updating public csv repo

- app/github_public_repo/estimate_csv_creator.py
> added print statements to track issue

- app/database_etl/airtable_records_handler/airtable_records_getter.py
> Added in debug for request response

- .github/workflows/run-etl.yml
- This updates the ETL GH Action to reduce the interval time for the client (our GH action runner) to send an empty packet to our EC2 instance to keep the connection alive for the entirety of the ETL run
- https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/receh7XbGLBR3kYqw?blocks=hide
- Ran the GH action against this branch and successfully ran. The SeroTracker website also reflects the changes.
- No
> Update ETL GH Action

- app/namespaces/data_provider/data_provider_controller.py
- app/namespaces/data_provider/data_provider_service.py
Updated the endpoints to return the most recent pub date as well as the last updated date
> updated endpoint

- app/serotracker_sqlalchemy/models.py
> added arborecords back

- Pathogens/Sero/API/Services/records_service.py
> Updated sc2 records service to only return details needed

- Pathogens/Sero/API/Services/records_service.py
> Updated backend endpoints to reduce clutter for sero

- Pathogens/Arbo/ETL/arbo_etl_main.py
Addresses https://github.com/PathoTracker/Pathotracker/issues/27
N/A
I've run a similar version of this script locally and couldn't find any estimates with a sample size of under 5 after my changes. The front end looks fine after my changes as well.
No
> Estimates with sample sizes of under 5 are no longer saved in the database

- .github/workflows/run-arbo-etl.yml
> Added arbo etl action
