app/utils/get_filtered_records.py

- Allow filters in the form {filter_key: []} to be passed in for frontend convenience.
- If an empty filter is passed in, it should not be applied (i.e. should let all records pass)

Allow empty filters to be passed in

---

app/namespaces/airtable_scraper/airtable_scraper_service.py

Prevent NaN values from being sent by the country_seroprev_summary endpoint. Send None's instead, which are JSON parseable

Hotfix for the filter issue

---

app/namespaces/data_provider/data_provider_service.py

add hyperlocal as estimate grade option for returning country seroprev summary. before this was not an option so filtering by hyperlocal was incorrect.

add hyperlocal as estimate grade

---

app/utils/helper_funcs.py

When making requests to the backend that have a ```start_date``` or ```end_date``` parameter, the web client will pass in an ISO 8601 datetime string whose timezone information is based on settings configured on the user's machine.
Typically, a substring in the form "+05:00"  is featured at the end of ISO 8601 datetime strings. This represents the offset associated with the timezone that's currently being considered (e.g. this would mean that the user is in UTC+5). However, for UK timezones (UTC+0), it is possible for that substring to be 'Z' (representing zero offset) or '+00:00'. 
The problem is that Python's datetime module does not support ISO 8601 strings that have 'Z'. Thus, this PR fixes this issue by replacing 'Z' characters coming in from the frontend with '+00:00'.
1. Run the …

Fix parsing of datetimes coming from GMT timezone

---

app/namespaces/data_provider/data_provider_controller.py

Previously we were setting the defaults of the research_fields and prioritize_estimates fields to be False and True respectively, and we set the type to be bool. But in python bool(True) = bool(False) = True because the value is set, so if you passed in research_fields = False it would still set the param to true (reverse logic for prioritize_estimates). I changed the param type to be a string and then manually set the bool val of the param based on the value of the string.

Fix param parsing for research_fields and prioritize_estimates

---

app/namespaces/meta_analysis/meta_analysis_controller.py
logging.cfg

- Change StreamHandler level to "ERROR" to ensure only error messages are outputted to the console
- Add logging statements to the meta analysis endpoint
- Ran the server locally and pointed a local version of the ST web client to it
- Navigated to the analyze tab and changed some filters
- Checked the logfile to ensure that the meta-analysis endpoint invocations were properly logged

Add logging to meta analysis namespace, suppress stream logging

---

app/database_etl/country_iso3.json

ETL cannot find the ISO3 code associated with the "Republic of Congo". This has lead to the following slack notification:
N/A
Ran the ETL locally, made sure that no logs around iso3 codes not being found were emitted.
No.

Add republic of congo's iso3 code

---

app/database_etl/postgres_tables_handler/postgres_utils.py

Sort countries in alpha order when displaying them as filter options.
https://airtable.com/tbli2lWQHAqBa6ZcI/recp2r0QEdNRhW1wL
Hit the /filter_options endpoint and verified.
No.

Sort countries in alpha order

---

app/namespaces/meta_analysis/meta_analysis_controller.py

- Meta analysis was throwing key errors when trying to aggregate records with the aggregation var if there were no records to aggregate
- No records occur if filters remove all records (e.g. source type = Publication is not a valid source type)
- Hit meta analysis endpoint using body in dev-logging-backend channel and see that empty dict is returned
- No but I realized that when we copy the request body from the dev-logging-backend channel it is not in JSON format because there are single quotes instead of double, so you have to modify to change to JSON format before inputting in postman
- @abeljoseph can you modify the script so that if the request body is "m", instead of adding just "m" to the error you add m = json.dumps(m)?

Meta analysis empty records fix

---

app/database_etl/tableau_data_connector/google_services_manager.py

- change path of pickle file and credentials.json to explicitly be in tableau_data_connector folder
- need to specify this bc the upload csv to gdrive func is being called outside that folder

changing path of creds files for google services manager

---

app/database_etl/airtable_records_handler/airtable_records_formatter.py

- in the ETL, we were getting an issue where if there were multiple first authors listed, the index that was computed was longer than the number of first authors, so it threw an index out of bounds error
- this is because for first_author, organizational_author, and source_type, there can be multiple of these three, and we should take the one corresponding to the max publication date
- in some cases, there may not be a first_author corresponding to the max pub date
- example: publication_dates: [2020-03-10, 2020-05,11]. The max pub date corresponds to index 1, so we should get the element of first_author, organizational_author, and source_type where index = 1. If first_author: [person], then first_author[1], is out of bounds. In this case, if the index is out of bounds, get the value with …

fix first_author index out of bounds error

---

app/namespaces/data_provider/data_provider_controller.py
app/namespaces/data_provider/data_provider_schema.py
app/utils/__init__.py
app/utils/get_filtered_records.py

Modified `get_pagination_records` to return a dictionary of lists of records (between a start and end page index). Previously, it returned a single page of records. 
[Ticket link](https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/receg2IU5tYhWuQzM?blocks=hide)
Made GET and POST requests with the pagination parameters and ensured the behaviour was correct
Nope!

 Updated pagination endpoint

---

app/database_etl/postgres_tables_handler/postgres_loader.py

`drop_table_entries` needs to explicitly look for entries with `created_at` = null when determining which entries to drop. 
Somehow on our production database, we inserted many records into `research_source` without a `created_at` field, they have not been deleted to this day. This PR should fix that.
N/A
Manually ran ETL locally, made sure that entries with null `created_at` values in all tables were deleted.
N/A

Fix drop tables

---

app/database_etl/postgres_tables_handler/postgres_utils.py
app/namespaces/data_provider/data_provider_controller.py
app/namespaces/data_provider/data_provider_schema.py
app/utils/estimate_prioritization.py
app/utils/get_filtered_records.py

1. Add bounds for publication date to /filter_options endpoint
2. Add option to pass in 'mode' for estimate_prioritization. Don't have to pass anything in, in which case mode defaults to None, otherwise can pass in analysis_dynamic or analysis_static
https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/reco3hpy0xYMEdZqw
- tested the /filter_options endpoint, and made sure was getting right values for bounds on pub date and sampling end date
- tested estimate prioritization with no mode, with correct modes, and incorrect modes (to test the schema check)
NO

Filter option changes

---

app/serotracker_sqlalchemy/db_model_config.py

- send these fields to dashboard: 'sensitivity', 'specificity', 'summary', 'study_type', 'source_publisher', 'lead_organization',
'first_author'
https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/recX5I9zu7Rz0ZnXb 
- tested dashboard get records endpoint to make sure these are pulled through by default
- no

Pull additional fields through to dashboard

---

app/database_etl/airtable_records_handler/airtable_records_formatter.py
app/database_etl/airtable_records_handler/airtable_records_getter.py

- Added a new column to airtable called 'ETL Included' that is 1 if Included, Serum pos prevalence, Denominator and Sampling End Date are all not blank, and 0 if any of them are blank
- Added a 'filterByFormula' term to the airtable API request to only pull fields where ETL Included = 1
- Removing code to drop rows where either of these 4 fields is null in the ETL
https://airtable.com/tbli2lWQHAqBa6ZcI/viwp6zUTCqlERLzMj/recMca3RyfhpOQYYO?blocks=hide 
- Checked to make sure that the number of records pulled from airtable when ETL Included = 1 is the same as the number of records without this filter after dropping null fields in ETL
- NO

Add 'ETL Included' filter to airtable API request

---

app/database_etl/postgres_tables_handler/postgres_utils.py
app/namespaces/data_provider/data_provider_schema.py

Adding `subgroup_var`, `subgroup_cat`, and `genpop` as valid filter options for the `data_provider/records` endpoint for research purposes 
None
Little testing beside code checks passing - not clear what would be necessary to actually test this functionality! 
Shouldn't be required -- modifications to existing code

Add subgroup filter options

---

app/utils/estimate_prioritization/pooling_functions.py

- Bug: internal server errors when calling /records endpoint
- Bugfix: Drop null entries in pooling function so that string concatenation won't fail
N/A
Tested locally (using Postman) with various filter combinations (no filters, country = canada, population group = residual sera, and combinations)
N/A

Fix EP Internal Server Errors

---

app/utils/estimate_prioritization/estimate_prioritization.py

- Internal server error when filters that return no data are given
N/A
Locally via postman with the following filter options:
```
{
"prioritize_estimates": true,
"research_fields": true,
"prioritize_estimates_mode": "analysis_dynamic",
"include_in_srma": true,
"filters": {
"genpop": ["Study examining general population seroprevalence"],
"subgroup_var": ["Race"],
"subgroup_cat": ["Caucasian"]
}
}
```
No

Return empty DF instead of None if there are no estimates to prioritize

---

app/database_etl/airtable_records_handler/airtable_records_formatter.py

Round all floats to equal precision to ensure consistent comparisons during testadj diffing
N/A
Ran ETL locally
Re-enable CI/CD

Round all floats to equal precision to ensure consistent comparisons during testadj diffing

---

app/database_etl/airtable_records_handler/airtable_records_formatter.py

- if there are no old records in db, should just end the test adj function early and return all new adjusted records

Adding handling of edge case where there are no old records

---

app/namespaces/data_provider/data_provider_service.py
app/utils/__init__.py
app/utils/get_filtered_records.py

Use sqlalchemy instead of python to perform record aggregation (after joining) to increase code simplicity
N/A
-Hit endpoint locally with certain filter combinations and ensured that the same number of records were retrieved (comparing against making sql queries on my local database)
- Pointed local serotracker.com web client to local server and made sure that all functionality worked as expected
- N/A

Use SQLAlchemy instead of python to aggregate records

---

app/namespaces/data_provider/data_provider_service.py
app/utils/get_filtered_records.py

- Bug: Get record details was returning an array of records instead of a single one. This was causing some record detail modals on the explore tab to appear buggy.
- Solution: Remove pythonic isotype string to list conversion and instead, have sqlalchemy query return an array right away
N/A
- Tested endpoints on postman
- Ran local app and performed regression testing
- N/A

fix get record details bug

---

app/database_etl/location_utils/country_alternative_names.json

Case and test data for some countries was not being pulled because these countries had different names in our data and in the Hopkins data. Augmented the mapping in our data to fix this. 
None. However, I have added a ticket to ensure that countries with missing data are identified automatically via Slack going forward. Ticket link: https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/recPEw7IDgiOWalqQ?blocks=hide
Ran ETL locally. 
No.

augment country_alternative_names.json

---

app/database_etl/postgres_tables_handler/table_formatter.py

When we map GBD regions, WHO regions, and other attributes to countries, we check to ensure that we have a mapping for every country. Previously, we were reporting None as a country which lacked attributes, but recently, we pushed a change to remove None options from the data. However, if there are no None options, `set.remove()` throws a `KeyError`. Substituting this with `set.discard()` fixes this.
None
Ran ETL locally
No

change remove to discard to prevent keyerrors

---

app/namespaces/data_provider/data_provider_controller.py
app/namespaces/data_provider/data_provider_schema.py
app/utils/get_filtered_records.py

Adds new flag to /records endpoint to allow us to query records with insufficient latlng data
N/A
Spun up local server and tested making requests to it
N/A, note that this should be merged to master before publishing changes to serosurvr @harrietware

Add include_records_without_latlngs flag

---

app/database_etl/postgres_tables_handler/postgres_utils.py

- "Household and community samples" was repeated twice in the static filter options for population group
-

Remove duplicate household and community samples from static filter options

---

app/database_etl/airtable_records_handler/__init__.py
app/database_etl/airtable_records_handler/airtable_records_formatter.py
app/database_etl/etl_main.py
app/database_etl/test_adjustment_handler/__init__.py
app/database_etl/test_adjustment_handler/test_adjustment.py
app/namespaces/test_adjustment/__init__.py
app/namespaces/test_adjustment/test_adjustment_schema.py
app/namespaces/test_adjustment/test_adjustment_service.py

- Some updates to the test adj model and sanity checks to make sure certain params are bounded correctly
- Making ETL use new test adj model that is being used by endpoint
- Moved the function in the ETL that applies diffing logic and runs test adj to the test adj folder in ETL (makes more sense to have it here)
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwDpHWCgFagItSc6/recyBq9zzIAb2kAVb?blocks=hide
- Ran the ETL locally for 48 estimates, sanity checked outputs
- Once this PR is approved, will need to run ETL on ALL estimates in prod

Add new test adj model to ETL

---

app/github_public_repo/README.md

The link to the Data Dictionary was updated. It now sends users to the Data Dictionary view created directly from the SOP in the "Airtable SOP" table instead of the separate dictionary in the "GitHub CSV Fields" table.
NA
Verified that the link sends the user to the correct Data Dictionary.
No.

Data Dictionary link update

---

app/database_etl/airtable_records_handler/airtable_records_formatter.py
app/database_etl/etl_main.py
app/database_etl/postgres_tables_handler/table_generator.py
app/namespaces/data_provider/data_provider_service.py

- PR adds in functionality to preserve "None" as an option in multi select tables (city, state, test manufacturer, antibody target_
- Also changing filter options to only return Spike and Nucleocapsid for antibody target as request by @rahularoradfs

Adding in None as option for multi select tables

---

app/database_etl/tableau_data_connector/table_generator.py
app/namespaces/data_provider/data_provider_controller.py
app/namespaces/data_provider/data_provider_schema.py
app/utils/get_filtered_records.py

1. This PR removes the /dashboard_records endpoint. The only endpoint available now is the /records endpoint
2. This PR removes the 'prioritize_estimates' bool param from the endpoint
3. This PR adds a parameter called estimates_subgroup that accepts three values: 'all'_estimates, 'prioritized_estimates', and 'primary_estimates'. The parameter is 'all' by default.
--> If 'all' is specified (or the param is left blank), ALL estimates will be returned (~13K estimates, multiple estimates per study)
--> If 'estimate_prioritization' is specified, only estimates output from estimate_prioritization will be returned
--> If 'primary_estimates', only the primary estimates of each study will be returned
- Will need coordinate deployment with frontend with @atatmaja and will need to coordinate …

Setting estimate prio bool to false

---

app/utils/get_filtered_records.py

- when called get records with 'primary_estimates' it would return NaN for some fields instead of null
- The line to convert NaN to null was only being used in the 'prioritize_estimates' logic block, so needed to copy over to do the same for primary estimates

Convert np.nan to null in primary estimates df

---

app/github_public_repo/estimate_csv_creator.py

- putting antibody_target and isotypes columns in a list and replacing Not reported values with None
- removing zotero_citation_key from list

Fixing csv for github and biblio

---

app/database_etl/airtable_records_handler/airtable_records_formatter.py

estimates csv generator script was not outputing the `antibody_target` and `isotype` columns as expected (refer to ticket).
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/rechvFUuXWyx4oaGA?blocks=hide
Ran the script again and the output was now showing as expected. Updated the public repo with the new CSV manually for the time-being

Fix estimates csv generator script
